---
- name: Deploy nodejs app
  hosts: 18.204.7.236
  tasks:
    - name: Copy nodejs folder to a server
      copy:
        src: /portal/company-hub/client/client-0.1.0.tgz
        dest: /home/ec2-user/client-0.1.0.tgz
    - name: Unpack the nodejs tar file
      unarchive:
        src: /home/ec2-user/client-0.1.0.tgz
        dest: /home/ec2-user/
        remote_src: yes
    - name: Install Dependencies
      npm:
        path: /home/ec2-user/package
    - name: Start the application
      command:
        chdir: /home/ec2-user/package
        cmd: npm start
      async: 1000
      poll: 0
      