---
- name: Install node and npm
  hosts: dev
  become: yes
  tasks:
    - name: Update repo and cache
      yum: 
        update_cache: yes 
    - name: Install nodejs and npm
      yum:
        name:
          - nodejs
          - npm
